### ISSUE TITLE
CLI -voxel size flag does not maintain orientation

### ISSUE THREAD

**Issue by bryantChhun** [brainglobe/brainreg#23]
In the code we have [this line](https://github.com/brainglobe/brainreg/blob/f8adaebb8c285c81d7daccbe5fc58a56be665aff/brainreg/cli.py#L134) that says:

> `Voxel sizes in microns, in the order of data orientation. `

However, I tried taking the test brain dataset as per [tutorial](https://docs.brainglobe.info/brainreg/tutorial), which specifies:

> `-v 50 40 40  --orientation psl`

and then rotate this using [bg_space](https://github.com/brainglobe/bg-space) to a sagittal orientation "rsp"

> `mapped_stack = bg.map_stack_to('psl', 'rsp', stack)`

Then when I run brainreg with the following command:

> `brainreg test_brain_rsp brainreg_output_rsp -v 40 40 50  --orientation rsp --atlas allen_mouse_50um`

I get an error:

```concurrent.futures.process._RemoteTraceback: 
"""
Traceback (most recent call last):
  File "/Users/bryant.chhun/anaconda3/envs/brainreg/lib/python3.8/concurrent/futures/process.py", line 239, in _process_worker
    r = call_item.fn(*call_item.args, **call_item.kwargs)
  File "/Users/bryant.chhun/anaconda3/envs/brainreg/lib/python3.8/site-packages/imio/load.py", line 459, in load_from_paths_sequence
    volume[:, :, i] = img
ValueError: could not broadcast input array from shape (193,270) into shape (154,270)
"""

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/Users/bryant.chhun/anaconda3/envs/brainreg/bin/brainreg", line 8, in <module>
Loading images:   0%|                                                                                                                                                                         | 0/68 [00:00<?, ?plane/s]    sys.exit(main())
  File "/Users/bryant.chhun/anaconda3/envs/brainreg/lib/python3.8/site-packages/brainreg/cli.py", line 193, in main
Loading images:   0%|                                                                                                                                                                         | 0/67 [00:00<?, ?plane/s]
    register(
  File "/Users/bryant.chhun/anaconda3/envs/brainreg/lib/python3.8/site-packages/brainreg/main.py", line 50, in main
    target_brain = imio.load_any(
  File "/Users/bryant.chhun/anaconda3/envs/brainreg/lib/python3.8/site-packages/imio/load.py", line 67, in load_any
    img = load_from_folder(
  File "/Users/bryant.chhun/anaconda3/envs/brainreg/lib/python3.8/site-packages/imio/load.py", line 239, in load_from_folder
    return load_image_series(
  File "/Users/bryant.chhun/anaconda3/envs/brainreg/lib/python3.8/site-packages/imio/load.py", line 330, in load_image_series
    img = threaded_load_from_sequence(
  File "/Users/bryant.chhun/anaconda3/envs/brainreg/lib/python3.8/site-packages/imio/load.py", line 404, in threaded_load_from_sequence
    stack = np.dstack([s.result() for s in stacks])
  File "/Users/bryant.chhun/anaconda3/envs/brainreg/lib/python3.8/site-packages/imio/load.py", line 404, in <listcomp>
    stack = np.dstack([s.result() for s in stacks])
  File "/Users/bryant.chhun/anaconda3/envs/brainreg/lib/python3.8/concurrent/futures/_base.py", line 439, in result
    return self.__get_result()
  File "/Users/bryant.chhun/anaconda3/envs/brainreg/lib/python3.8/concurrent/futures/_base.py", line 388, in __get_result
    raise self._exception
ValueError: could not broadcast input array from shape (193,270) into shape (154,270)
```

This error is resolved if I change the voxel orientation back to:

> `brainreg test_brain_rsp brainreg_output_rsp -v 50 40 40  --orientation rsp --atlas allen_mouse_50um`

Additionally, the above line outputs an atlas in Coronal orientation.  It would be nice if the output files are sliced similarly to the input.  But this is not critical and probably worth a separate issue.

**Comment by adamltyson** [comment]
Thanks for catching this @bryantChhun, there was an error in the IO package. Could you try updating (`pip install imio --upgrade`) and trying again?

> Additionally, the above line outputs an atlas in Coronal orientation. It would be nice if the output files are sliced similarly to the input. But this is not critical and probably worth a separate issue.

I've thought about this (the old registration package did this), and I've decided to keep it as it is, as it simplifies a lot of downstream workflows. For visualisation, napari allows you to easily reslice, and if you need the data reoriented for other purposes, then you can use `bg_space`.

**Comment by adamltyson** [comment]
Hi @bryantChhun, has this fixed the issue?

**Comment by adamltyson** [comment]
Closing now. Feel free to reopen @bryantChhun if the issue persists.
