### ISSUE TITLE
Tutorial bug:  The process cannot access the file because it is being used by another process

### ISSUE THREAD

**Issue by xy103** [brainglobe/brainreg#53]
Hi I'm trying to run the tutorial for brainreg and kept getting the following error. Could someone take a look and help? Thanks!

Traceback (most recent call last):
  File "C:\Users\xinto\anaconda3\envs\brainreg_env\lib\runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\Users\xinto\anaconda3\envs\brainreg_env\lib\runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "C:\Users\xinto\anaconda3\envs\brainreg_env\Scripts\brainreg.exe\__main__.py", line 7, in <module>
  File "C:\Users\xinto\anaconda3\envs\brainreg_env\lib\site-packages\brainreg\cli.py", line 207, in main
    register(
  File "C:\Users\xinto\anaconda3\envs\brainreg_env\lib\site-packages\brainreg\main.py", line 65, in main
    run_niftyreg(
  File "C:\Users\xinto\anaconda3\envs\brainreg_env\lib\site-packages\brainreg\backend\niftyreg\run.py", line 214, in run_niftyreg
    delete_directory_contents(niftyreg_directory)
  File "C:\Users\xinto\anaconda3\envs\brainreg_env\lib\site-packages\imlib\general\system.py", line 351, in delete_directory_contents
    os.remove(os.path.join(directory, f))
PermissionError: [WinError 32] The process cannot access the file because it is being used by another process: 'C:\\Users\\xinto\\Desktop\\test_brain\\output\\niftyreg\\deformation_field.nii'

**Comment by adamltyson** [comment]
Hey @xy103, thanks for raising this. It seems to be a new issue on Windows. I'll try to take a look, but no ETA I'm afraid.

**Comment by adamltyson** [comment]
I can't reproduce this on Windows, so I'm going to close. Feel free to reopen if the problem persists and I'll try to track it down.
