### ISSUE TITLE
Error finding libpng files

### ISSUE THREAD

**Issue by dstansby** [brainglobe/brainreg#58]
I'm trying to run thrhough the `brainreg` tutorial, and am getting the following error:

```python
Traceback (most recent call last):
  File "/Users/dstansby/mambaforge/envs/napari/lib/python3.9/site-packages/imlib/general/system.py", line 281, in safe_execute_command
    subprocess.check_call(
  File "/Users/dstansby/mambaforge/envs/napari/lib/python3.9/subprocess.py", line 373, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '"/Users/dstansby/mambaforge/envs/napari/lib/python3.9/site-packages/brainreg/bin/nifty_reg/osX/reg_aladin" -ln 6 -lp 5 -flo "brainreg_output/niftyreg/brain_filtered.nii" -ref "brainreg_output/niftyreg/downsampled_filtered.nii" -aff "brainreg_output/niftyreg/affine_matrix.txt" -res "brainreg_output/niftyreg/affine_registered_atlas_brain.nii" -omp 4' died with <Signals.SIGABRT: 6>.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/dstansby/mambaforge/envs/napari/lib/python3.9/site-packages/brainreg/backend/niftyreg/registration.py", line 73, in register_affine
    safe_execute_command(
  File "/Users/dstansby/mambaforge/envs/napari/lib/python3.9/site-packages/imlib/general/system.py", line 293, in safe_execute_command
    raise SafeExecuteCommandError(
imlib.general.system.SafeExecuteCommandError: 
-------------------------
Process failed:
 dyld[51445]: Library not loaded: /usr/local/opt/libpng/lib/libpng16.16.dylib
  Referenced from: /Users/dstansby/mambaforge/envs/napari/lib/python3.9/site-packages/brainreg/bin/nifty_reg/osX/reg_aladin
  Reason: tried: '/usr/local/opt/libpng/lib/libpng16.16.dylib' (no such file), '/usr/local/lib/libpng16.16.dylib' (no such file), '/usr/lib/libpng16.16.dylib' (no such file)
-------------------------

-------------------------
please read the logs at brainreg_output/niftyreg/affine.log and brainreg_output/niftyreg/affine.err
-------------------------
command: "/Users/dstansby/mambaforge/envs/napari/lib/python3.9/site-packages/brainreg/bin/nifty_reg/osX/reg_aladin" -ln 6 -lp 5 -flo "brainreg_output/niftyreg/brain_filtered.nii" -ref "brainreg_output/niftyreg/downsampled_filtered.nii" -aff "brainreg_output/niftyreg/affine_matrix.txt" -res "brainreg_output/niftyreg/affine_registered_atlas_brain.nii" -omp 4
-------------------------

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/dstansby/mambaforge/envs/napari/bin/brainreg", line 8, in <module>
    sys.exit(main())
  File "/Users/dstansby/mambaforge/envs/napari/lib/python3.9/site-packages/brainreg/cli.py", line 207, in main
    register(
  File "/Users/dstansby/mambaforge/envs/napari/lib/python3.9/site-packages/brainreg/main.py", line 65, in main
    run_niftyreg(
  File "/Users/dstansby/mambaforge/envs/napari/lib/python3.9/site-packages/brainreg/backend/niftyreg/run.py", line 82, in run_niftyreg
    brain_reg.register_affine()
  File "/Users/dstansby/mambaforge/envs/napari/lib/python3.9/site-packages/brainreg/backend/niftyreg/registration.py", line 79, in register_affine
    raise RegistrationError(
brainreg.backend.niftyreg.registration.RegistrationError: Affine registration failed; 
-------------------------
Process failed:
 dyld[51445]: Library not loaded: /usr/local/opt/libpng/lib/libpng16.16.dylib
  Referenced from: /Users/dstansby/mambaforge/envs/napari/lib/python3.9/site-packages/brainreg/bin/nifty_reg/osX/reg_aladin
  Reason: tried: '/usr/local/opt/libpng/lib/libpng16.16.dylib' (no such file), '/usr/local/lib/libpng16.16.dylib' (no such file), '/usr/lib/libpng16.16.dylib' (no such file)
-------------------------
```

It looks like this is an issue with the `niftyreg` binaries that are bundled. I'm on an M1 Mac with macOS 12.2.1, Python 3.10.

**Comment by adamltyson** [comment]
I don’t know why it’s no longer in the readme, but macOS is basically not supported due to the issues compiling the libraries for different versions (not to mention M1). 

It’s rarely a problem as brainreg is typically run on high-memory workstations.

**Comment by adamltyson** [comment]
@dstansby, if you have `homebrew`, `brew install libpng` fixed this for me (on an Intel mac).

**Comment by dstansby** [comment]
`brew install libpng` installs `libpng` fine for me, but it installs it to `/opt/homebrew/opt/libpng`, and `niftyreg` is looking for one of

- '/usr/local/opt/libpng/lib/libpng16.16.dylib' (no such file),
-  '/usr/local/lib/libpng16.16.dylib' (no such file),
- '/usr/lib/libpng16.16.dylib' (no such file)

**Comment by adamltyson** [comment]
@dstansby I've added #77 to track supporting macOS. Do you think we can close this issue?

**Comment by dstansby** [comment]
Yep, I think now it's on conda this shouldn't be an issue (with the right installation instructions)
