### ISSUE TITLE
Having an error while registering

### ISSUE THREAD

**Issue by bpavie** [brainglobe/brainreg#9]
Dear,

I tried to use the software on windows but I have got an error during the process:

```
brainreg "E:/dataset" "E:/output" -x 1.38 -y 1.38 -z 1 --atlas allen_mouse_25um
This version of slurmio (0.0.4) is not the most recent version. Please update to v0.0.5 by running: 'pip install slurmio --upgrade' 
INFO:root:Starting logging
2020-07-24 14:19:40 PM - INFO - MainProcess fancylog.py:277 - Starting logging
INFO:root:Not logging multiple processes
2020-07-24 14:19:40 PM - INFO - MainProcess fancylog.py:278 - Not logging multiple processes
INFO:root:Starting registration
2020-07-24 14:19:40 PM - INFO - MainProcess cli.py:210 - Starting registration
Bgatlas_api: None not found locally. Downloading...
Traceback (most recent call last):
  File "d:\sofware\miniconda3\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "d:\sofware\miniconda3\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "D:\SOFWARE\Miniconda3\Scripts\brainreg.exe\__main__.py", line 7, in <module>
  File "d:\sofware\miniconda3\lib\site-packages\brainreg\cli.py", line 234, in main
    run()
  File "d:\sofware\miniconda3\lib\site-packages\brainreg\cli.py", line 212, in run
    atlas = BrainGlobeAtlas(args.atlas)
  File "d:\sofware\miniconda3\lib\site-packages\bg_atlasapi\bg_atlas.py", line 71, in __init__
    self.download_extract_file()
  File "d:\sofware\miniconda3\lib\site-packages\bg_atlasapi\bg_atlas.py", line 139, in download_extract_file
    utils.retrieve_over_http(self.remote_url, destination_path)
  File "d:\sofware\miniconda3\lib\site-packages\bg_atlasapi\bg_atlas.py", line 126, in remote_url
    maj, min = self.remote_version
  File "d:\sofware\miniconda3\lib\site-packages\bg_atlasapi\bg_atlas.py", line 99, in remote_version
    versions_conf["atlases"][self.atlas_name]
  File "d:\sofware\miniconda3\lib\configparser.py", line 1250, in __getitem__
    if not self._parser.has_option(self._name, key):
  File "d:\sofware\miniconda3\lib\configparser.py", line 885, in has_option
    option = self.optionxform(option)
  File "d:\sofware\miniconda3\lib\configparser.py", line 873, in optionxform
    return optionstr.lower()
AttributeError: 'NoneType' object has no attribute 'lower'
```

It looks like it can't find the atlas.
I trie to download it using 
```
brainglobe install -a allen_mouse_25um
```

The installation was successful and everything was saved in:
```C:\bin\cygwin\home\myusername\.brainglobe\allen_mouse_25um_v0.3```

But running again the registration gave me the same error, making me think that it may not look at the right place to find the Atlas.

BrainReg was installed using pip : `pip install brainreg`

Benjamin

**Comment by vigji** [comment]
Hi @bpavie, thank you for giving this a try and sorry for the instability, we are still adjusting code a bit on that side of things.
If it is placed there it should be found...could you:
0) provide version of `bg_atlasapi` module
1) Locate where is your `bg_atlasapi` module, try to look if inside you can find a `bg_config.conf` file and paste the content;
2) What happens if you open a python terminal and you just run:

```
from bg_atlasapi import BrainGlobeAtlas  
BrainGlobeAtlas("allen_mouse_25um")
```

**Comment by adamltyson** [comment]
Hi @vigji, @bpavie .

I can look into this next week, but there's also a good chance that there is an issue in the brainreg pip package. I wasn't aware that anyone was using it yet, so nothing has been tested.

**Comment by bpavie** [comment]
Thanks for the quick reply,
@vigji
content of `bg_config.conf`

```
[default_dirs]
brainglobe_dir = C:\bin\cygwin\home\myusername\.brainglobe
interm_download_dir = C:\bin\cygwin\home\myusername\.brainglobe
```

@adamltyson Do you have a recommended way on how to install it from github?

Benjamin

**Comment by vigji** [comment]
Ok, everything should be fine over there...then try to install the latest using:

```
python -m pip install git+https://github.com/brainglobe/bg-atlasapi
```

That might fix it, but if the problem is within brainreg you would have to wait @adamltyson.

**Comment by bpavie** [comment]
Thanks, I reinstalled brainreg:
```
pip install git+https://github.com/brainglobe/bg-atlasapi
pip install git+https://github.com/brainglobe/brainreg
```

Then re-run and it looks like the Atlas is now donwloaded, although I now have another error:

```
brainreg "E:/dataset" "E:/output" -x 1.38 -y 1.38 -z 1 --atlas allen_mouse_25um
This version of slurmio (0.0.4) is not the most recent version. Please update to v0.0.5 by running: 'pip install slurmio --upgrade'
INFO:root:Starting logging
2020-07-24 16:59:10 PM - INFO - MainProcess fancylog.py:277 - Starting logging
INFO:root:Not logging multiple processes
2020-07-24 16:59:10 PM - INFO - MainProcess fancylog.py:278 - Not logging multiple processes
INFO:root:Starting registration
2020-07-24 16:59:10 PM - INFO - MainProcess cli.py:210 - Starting registration allen mouse atlas (res. 25um)
From: http://www.brain-map.org.com (Wang et al 2020, https://doi.org/10.1016/j.cell.2020.04.007 )
DEBUG:root:Determining the maximum number of CPU cores to use
DEBUG:root:Number of CPU cores available is: 8
DEBUG:root:Setting number of processes to: 8
INFO:root:Loading raw image data
2020-07-24 16:59:12 PM - INFO - MainProcess main.py:70 - Loading raw image data
DEBUG:root:Data type is: directory of files
DEBUG:root:Determining the maximum number of CPU cores to use
DEBUG:root:Number of CPU cores available is: 8
DEBUG:root:Setting number of processes to: 8

This version of slurmio (0.0.4) is not the most recent version. Please update to v0.0.5 by running: 'pip install slurmio --upgrade'
Loading images: 100%|█████████████████████████| 1/1 [00:02<00:00,  2.88s/plane]
filtering: 100%|██████████████████████████| 456/456 [00:14<00:00, 31.11plane/s]
C:\Users\bpavie\AppData\Roaming\Python\Python37\site-packages\tifffile\tifffile.
py:1170: UserWarning: saving zero size array to nonconformant TIFF
  'saving zero size array to nonconformant TIFF', UserWarning
filtering: 100%|████████████████████████| 413/413 [00:00<00:00, 5708.87plane/s]
Traceback (most recent call last):
  File "d:\sofware\miniconda3\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "d:\sofware\miniconda3\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "D:\SOFWARE\Miniconda3\Scripts\brainreg.exe\__main__.py", line 7, in <module>
  File "d:\sofware\miniconda3\lib\site-packages\brainreg\cli.py", line 234, in main
    run()
  File "d:\sofware\miniconda3\lib\site-packages\brainreg\cli.py", line 227, in run
    debug=args.debug,
  File "d:\sofware\miniconda3\lib\site-packages\brainreg\main.py", line 108, in main
    n_free_cpus,
  File "d:\sofware\miniconda3\lib\site-packages\brainreg\backend\niftyreg\run.py", line 50, in run_niftyreg
    target_brain = preprocess.filter_image(target_brain)
  File "d:\sofware\miniconda3\lib\site-packages\brainreg\utils\preprocess.py", line 17, in filter_image
    brain = scale_and_convert_to_16_bits(brain)
  File "d:\sofware\miniconda3\lib\site-packages\imlib\image\scale.py", line 25,
in scale_and_convert_to_16_bits
    img = scale_to_16_bits(img)
  File "d:\sofware\miniconda3\lib\site-packages\imlib\image\scale.py", line 12,
in scale_to_16_bits
    normalised = img / img.max()
  File "C:\Users\myuser\AppData\Roaming\Python\Python37\site-packages\numpy\core\_methods.py", line 30, in _amax
    return umr_maximum(a, axis, None, out, keepdims, initial, where)
ValueError: zero-size array to reduction operation maximum which has no identity
```

The dataset I am trying to register contain only one slice, could it be the problem?

Benjamin

**Comment by vigji** [comment]
Yeah I believe so; I leave last word to @adamltyson but 99% sure there's no way you can use the current package for individual slices, only for volumetric data

**Comment by adamltyson** [comment]
Yep, for this package, the data must (currently) be an entire brain. The docs will eventually make this clear. 

At some point subvolumes will be accepted, and there is another package in development (but not yet useable) for slice data.

**Comment by bpavie** [comment]
Thanks to both of you for the very fast answer!

**Comment by adamltyson** [comment]
If you're interested in the development of the 2D version of this, it will be developed [here](https://github.com/slicereg/slicereg). If you like, I can add you to the GitHub organisation so you can receive updates about the progress.

**Comment by xcccc402** [comment]
Hi Tyson I am wondering if the current release of brainreg allows subvolumes registration? If yes, how many serial brain slices are needed at least (say coronal slices in 50 um thickness for example).

**Comment by adamltyson** [comment]
Hi @xcccc402 - unfortunately this feature has not yet been added, and there's no ETA. If there is any progress, we will update https://github.com/brainglobe/brainreg/issues/6.
